### ISSUE TITLE
plugin does not appear

### ISSUE THREAD

**Issue by vivi-gomez** [tgiesselmann/gimp-stable-boy#1]
Hi, Thank you for your plugin.
I am trying to make it work with Gimp 2.10.32 and Automatic1111 over windows11. Actually I can use SD with Krita, but cannot run your plugin and maybe I missing something.

I cloned you repo and added the folder direction in the gimp preference but I dont see any Stable Boy menu anywhere. I can say that I can install and see the AI menu from the Gimp Plugin from blueturtleai.

**Comment by RockLight3000** [comment]
Same here with a clean install of Gimp 2.10.32

**Comment by thndrbrrr** [comment]
Thanks for reporting this, @txirrindulari. @RockLight3000 You're also on Windows?

It would be helpful if you could start GIMP from the command line and post any relevant error messages. Log files work too.

Also, could you please post your GIMP plugin search paths here? Thank you.

**Comment by thndrbrrr** [comment]
@txirrindulari @RockLight3000 Looks like for some reason the file encoding wasn't correct. Fixed it. Can you try again?

**Comment by danielalcalde** [comment]
There seem to be quite a lot of bugs when trying to use the plugin with windows.
I managed to fix 2 until now:
First, there is a weird behavior where the params file does not properly get imported.
Second, line 212 should be ```url=kwargs['api_base_url'] + "/" + str(uri)```, web addresses should not be joined with os.path.join.

will continue fixing them until I get an image :)

**Comment by danielalcalde** [comment]
have it working on windows now

**Comment by thndrbrrr** [comment]
Thank you for the fix, @danielalcalde.
