### ISSUE TITLE
No module named gimpfu

### ISSUE THREAD

**Issue by beothorn** [tgiesselmann/gimp-stable-boy#2]
What is the issue:
The menu is not showing up

gimp -version
GNU Image Manipulation Program version 2.10.30

OS:
Linux  5.15.0-53-generic #59-Ubuntu SMP x86_64 GNU/Linux

Logs:
➜  gimp-stable-boy git:(main) gimp
Gtk-Message: 00:41:34.917: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/home/carol/dev/gimp-stable-boy/src/gimp-stable-boy/gimp-stable-boy.py", line 26, in <module>
    import gimpfu
ImportError: No module named gimpfu
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error

**Comment by beothorn** [comment]
Related:
https://stackoverflow.com/questions/69962119/error-importerror-no-module-named-gimpfu-in-gimp-plugin

Maybe the readme needs some more information or maybe there is an alternative to gimpfu.

**Comment by thndrbrrr** [comment]
Thanks, @beothorn. [This reply](https://stackoverflow.com/a/69965123/17757799) in particular seems to have the fix.

I'll update the README.

**Comment by beothorn** [comment]
Thanks, I will install gimp with flatpak which seems to be the less painful solution.
I think the only way to avoid this would be rewrite the whole plugin in another language :)

**Comment by thndrbrrr** [comment]
@beothorn I can get it started from the command line when I set the `PYTHONPATH` to GIMP's Python lib:

```sh
PYTHONPATH=/Applications/GIMP.app/Contents/Resources/lib/gimp/2.0/python
```

BTW, adding this line to a `.env` file in the root folder also also helps resolving the `gimfu` package in VSCode.
