### ISSUE TITLE
Plugin Fails to Load

### ISSUE THREAD

**Issue by Echostorm44** [tgiesselmann/gimp-stable-boy#21]
Hi there, bummed I can't get this going, it looks like a really useful feature from the videos.

Windows 10 64x
Python 3.10.9

Here is the relevant bit from the --verbose output when Gimp is loading:

```
Querying plug-in: 'E:\GimpAI\gimp-stable-boy\src\main.py'
C:\Program Files\GIMP 2\bin\gimp-2.10.exe: LibGimpBase-WARNING: gimp-2.10.exe: gimp_wire_read(): error
Querying plug-in: 'C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\file-rawtherapee\file-rawtherapee.exe'
Querying plug-in: 'C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\file-darktable\file-darktable.exe'
```

**Comment by thndrbrrr** [comment]
Unfortunately GIMP 2.10 still uses Python 2, so I wonder if that's the issue?

**Comment by Echostorm44** [comment]
I'm given to understand Gimp 2 supports Python 3 plugins using GObject Introspection

**Comment by thndrbrrr** [comment]
Hmm, I don't know the details around that. But even so – if GIMP (using
Python 2) has some ways of dealing with scripts written in Python 3 ...
that would still require Python 2 in the first place though, no?

Apart from that: Stable Boy is implemented in Python 2.

I'd definitely like to port it to Python 3, but I don't want to break
compatibility with GIMP 2.10 until GIMP 3 is ready for prime time.

Unless there's a way to make it compatible for both without requiring
obscure installation steps / hacks then it'll have to wait. I wouldn't want
two code bases.

**Comment by Echostorm44** [comment]
Don't blame you at all, one is enough. I'll look forward to trying it out when Gimp 3 comes out.
