### ISSUE TITLE
Stable Boy menu not showing

### ISSUE THREAD

**Issue by JasonS09** [tgiesselmann/gimp-stable-boy#22]
Hi. I tried to install the plugin but I'm having this unexpected issue. Stable Boy menu is not showing at all. I ran the program with verbose but all I get is this error, and I'm not even sure it's related:

> Querying plug-in: 'C:\Users\jason\Stable Diffusion\gimp-stable-boy\src\main.py
> C:\Program Files\GIMP 2\bin\gimp-2.10.exe: LibGimpBase-ADVERTENCIA: gimp-2.10.exe: gimp_wire_read(): error

I have also checked pluginrc but it doesn't seem to be registered.

I'm a Windows 11 user.

**Comment by Cookie2243** [comment]
I'm on windows 11 and have similar problem, no menu is showing.

**Comment by nebetsu** [comment]
I'm on Windows 10 and the Stable Boy kicking on for me either. 
>Querying plug-in: 'C:\Users\nebet\gimp-stable-boy\src\main.py'
>gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error

**Comment by sina-masoud-ansari** [comment]
Same issue here, Windows 10, GIMP 2.10.28

**Comment by thndrbrrr** [comment]
The most likely reason is that Python 2 isn't installed: https://stackoverflow.com/a/69965123/17757799

**Comment by Koech** [comment]
I installed the Gimp listed in that flatpak, and I am still getting the following error:
Querying plug-in: 'D:\stable_diffusion\Stable_Boy\src\main.py'
gimp-2.10.exe: LibGimpBase-WARNING: gimp-2.10.exe: gimp_wire_read(): error

I'm a windows 10 user, using a fresh install from that flatpak.

**Comment by dzehme** [comment]
I am seeing the same problem with Windows 11, Gimp 2.10.32

```
Querying plug-in: 'D:\gimp-stable-boy\src\main.py'
gimp-2.10.exe: LibGimpBase-WARNING: gimp-2.10.exe: gimp_wire_read(): error
```

Python 2 is also definitely installed as I can bring up the Python Fu console:

```
GIMP 2.10.32 Python Console
Python 2.7.18 (default, Oct 27 2021, 07:49:35)  [GCC 11.2.0 64 bit (AMD64)]
>>> 
```

**Comment by GitAcas** [comment]
> I am seeing the same problem with Windows 11, Gimp 2.10.32
> 
> ```
> Querying plug-in: 'D:\gimp-stable-boy\src\main.py'
> gimp-2.10.exe: LibGimpBase-WARNING: gimp-2.10.exe: gimp_wire_read(): error
> ```
> 
> Python 2 is also definitely installed as I can bring up the Python Fu console:
> 
> ```
> GIMP 2.10.32 Python Console
> Python 2.7.18 (default, Oct 27 2021, 07:49:35)  [GCC 11.2.0 64 bit (AMD64)]
> >>> 
> ```

same here

**Comment by GitAcas** [comment]
i noticed that menu works with old Gimp 2.8 , text to image works too with this version, but inpainting fails with 
Procedure "gimp-edit-paste-as-new-image" not found, so i guess gimp 2.10 is still needed to work fine

**Comment by GitAcas** [comment]
i found a stupid workaround for 2.10.32. if you put the content of the src folder under the very python of gimp (for example C:\Program Files\GIMP 2\lib\gimp\2.0\python ) and use that directory as plugin, the menu works. I guess it's really some sort of python set path missing

**Comment by Koech** [comment]
I can confirm, GitAcas's work around does fix it. But it's pretty obnoxious, since Gimp will query the entire python folder for plugins every startup, which... isn't ideal.

**Comment by HuReMD** [comment]
> i found a stupid workaround for 2.10.32. if you put the content of the src folder under the very python of gimp (for example C:\Program Files\GIMP 2\lib\gimp\2.0\python ) and use that directory as plugin, the menu works. I guess it's really some sort of python set path missing

> I can confirm, GitAcas's work around does fix it. But it's pretty obnoxious, since Gimp will query the entire python folder for plugins every startup, which... isn't ideal.

Work around doesn't work for me.

Windows 10
Python 2.7.18
Python 3.10.9
GIMP 2.10.32 (revision 1)
All other plugins work for me without any tiniest fuzz.

Edit: Gimp2.10.32 (not rev1 version) works.
I found out that Gimp revision 1 download text is subtle "gimp-2.10.32-setup-1", while Gimp non rev1 is "gimp-2.10.32-setup". Revision 1 may have some changes that affects plugins and others may have had rev1 version and thought it as non rev1 version. After looking at Gimp Help About GIMP I noticed I had rev 1 version.

Suggestion for future related issues. Check if you you have Gimp rev1 version, if so, take non rev1 version. It should work.

**Comment by reserved-word** [comment]
Apparently I found a solution for Windows. There is a known [issue](https://stackoverflow.com/questions/54235279/gimp-2-10-python-how-to-import-custom-module) where the interpreter cannot find modules. 

Solution:

move lines 
```
path = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(1, path)
```
before
`import gimp_stable_boy `

Win 10
Gimp: 2.10.32 **rev1** 
Python: included in GIMP Win distro

**Comment by thndrbrrr** [comment]
@GitAcas that'a quick and easy workaround indeed. Thanks! 👍 I'll mention that in the Readme.

**Comment by thndrbrrr** [comment]
@reserved-word thanks for sharing this. 🤩 There was an issue with Windows paths in a previous version, but that was fixed. I can only imagine that I reintroduced the problem when I refactored everything over Christmas.

Care to submit a patch? 🤓

I'll definitely setup up Windows 11 in a VM for testing.

**Comment by Koech** [comment]
I can verify that the above fix works (and is a huge relief since it no longer tries to pull all of the python scripts in the folder.)

I've submitted a patch with the fix implemented.

**Comment by thndrbrrr** [comment]
Finally got around to merging @Koech's PR – thanks, @Koech!
