### ISSUE TITLE
Cant undertand the steps 3 and 4

### ISSUE THREAD

**Issue by NicoBueno666** [tgiesselmann/gimp-stable-boy#24]
Hello, there. Sorry for this issue, but I coundt undertand the staps 3 and 4 from the instalation guide.

Can anyone explain this steps?

STEP 3: Start A1111 WebUI with argument --api. It doesn't matter whether it's running on your local machine or somewhere in the cloud.
STEP 4: Open Stable Boy's preferences (top menu > Stable Boy > Preferences) and copy-paste A1111 WebUI's URL (something like https://abcdef123.gradio.com) into the API URL field.

**Comment by thndrbrrr** [comment]
Hi @NicoBueno666 – step 3 is about launching [AUTOMATIC1111's Stable Diffusion WebUI](https://github.com/AUTOMATIC1111/stable-diffusion-webui) with the option `--api`. So you'll have to have that project cloned and built somewhere, either locally or on Google Colab or similar.

Once you have done so it'll print out the API's URL and that's what you have to paste into Stable Boy's preferences (in GIMP, in the Stable Boy top menu).

**Comment by NicoBueno666** [comment]
Thanks a lot, @thndrbrrr , I could make it work in Google Colab! Amazing job!

**Comment by thndrbrrr** [comment]
That's awesome to hear! Now go forth and create amazing things! ✌️🤩
