### ISSUE TITLE
On slow networks, gimp becomes unresponsive

### ISSUE THREAD

**Issue by beothorn** [tgiesselmann/gimp-stable-boy#6]
On slow networks, gimp becomes unresponsive

A message shows up saying Gimp is unresponsive and asks if I want to wait or quit gimp.

![image](https://user-images.githubusercontent.com/410600/205505941-57d36f98-748e-4213-8746-554c344079d2.png)

If there is such a thing, a dialog that runs this task in a separate thread and a progress bar would fix it.

**Comment by beothorn** [comment]
see #12

**Comment by thndrbrrr** [comment]
See [cf4681e](https://github.com/tgiesselmann/gimp-stable-boy/commit/cf4681ecca6b96402b3bbb58688e5348ca103201) ✅
