### ISSUE TITLE
GIMP 2.10 not picking up plugin

### ISSUE THREAD

**Issue by bobdobbs** [tgiesselmann/gimp-stable-boy#9]
I'm using GIMP 2.10.30 on Ubuntu 22.04.

I've installed the plugin in ~/opt/
So the full path to the src directory is /home/[username]/opt/gimp-stable-boy/src/gimp-stable-boy

I attempted configured GIMP to be aware of gimp-stable-boy plugin by going to 'edit'->'preferences'->'folders'->'Plug-Ins', opening the 'Plug-in Folders' UI, and adding the path to the absolute path.

I made sure to point to the subfolder '.../src/gimp-stable-boy'.

Attempts to configure the path failed: after restart I could not find a 'gimp stable boy' menu anywhere.

I thought that maybe I was failing to configure the path properly because I was adding the path by typing it in by hand and also pasting in the path to the UI.

So I used the Plug-In Folder UI option that opens up a file navigation dialogue, and I used that to navigate to the '.../src/gimp-stable-boy' folder.

After restarting, I still can't see a menu anywhere for the plugin.

**Comment by danielalcalde** [comment]
you can start gimp from the terminal with gimp --verbose and see if you get any error

**Comment by bobdobbs** [comment]
@danielalcalde I think I might have found the issue, but I'm not sure.
Output from 'gimp --verbose' did indeed lead me towards these possible issues.

gimp-stable-boy has python2 dependencies. Some of them might by simple to replace, some of them not so much.

Ubuntu 22.04 (and other distros) have python3 as system python.
Python3 doesn't have gimpfu.

I'm afraid I don't have any suggestions about what to do here, because I don't know enough about these deps.

I'm currently looking into running gimp from the flatpak installer. 
I think that this version comes pre-packaged with most of it's deps.
But as far as I can tell there is no official flatpak distribution of GIMP, and the versions that I've found are out of date (even if only slightly).

**Comment by thndrbrrr** [comment]
Thank you for following up, @bobdobbs. Pretty sure there is a way to have multiple Python versions on Ubuntu? :)

Closing this since it seems to be a GIMP / Python compatibility issue.
